### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by zuwuko** [takeit/superdesk-install#1]
Installing on a fresh Digital Ocean Ubuntu 16.04 64bit base running the provided github superdesk install file:

INFO:superdesk:Uhoh, an exception occured while running the command...
ERROR:superdesk:Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'
Traceback (most recent call last):
  File "/opt/superdesk/env/lib/python3.5/site-packages/superdesk/__init__.py", line 60, in __call__
    res = self.run(*args, **kwargs)
  File "/opt/superdesk/env/lib/python3.5/site-packages/apps/prepopulate/app_initialize.py", line 230, in run
    app.init_indexes()
  File "/opt/superdesk/env/lib/python3.5/site-packages/superdesk/factory/app.py", line 59, in init_indexes
    create_index(self, resource, name, list_of_keys, index_options)
  File "/opt/superdesk/env/lib/python3.5/site-packages/eve/io/mongo/mongo.py", line 969, in create_index
    db = app.data.pymongo(resource, px).db
  File "/opt/superdesk/env/lib/python3.5/site-packages/superdesk/datalayer.py", line 41, in pymongo
    return self.mongo.pymongo(resource, prefix)
  File "/opt/superdesk/env/lib/python3.5/site-packages/eve/io/mongo/mongo.py", line 893, in pymongo
    self.driver[px] = PyMongo(self.app, px)
  File "/opt/superdesk/env/lib/python3.5/site-packages/flask_pymongo/__init__.py", line 116, in __init__
    self.init_app(app, uri, *args, **kwargs)
  File "/opt/superdesk/env/lib/python3.5/site-packages/flask_pymongo/__init__.py", line 149, in init_app
    parsed_uri = uri_parser.parse_uri(uri)
  File "/opt/superdesk/env/lib/python3.5/site-packages/pymongo/uri_parser.py", line 357, in parse_uri
    "begin with '%s' or '%s'" % (SCHEME, SRV_SCHEME))
pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://' or 'mongodb+srv://'

**Comment by takeit** [comment]
@petrjasek any ideas?

**Comment by petrjasek** [comment]
yep this should be fixed already, will check if that install branch got updated

**Comment by alexsolis23** [comment]
hello, im sorry if Im not suppossed to write in here, but Im getting an error when I try to run sudo apt-get install curl -y && curl -s https://raw.githubusercontent.com/takeit/superdesk-install/master/install | sudo bash  

the repository 'https://packages.elastic.co/elasticsearch/1.7/debian stable Release' is not signed
by any chance do you know why? I've tried everything, I've even clean installed 3 times already

**Comment by trondhuso** [comment]
@alexsolis23 You (or the script) are most likely running against an old repo with an old public key.
